### ISSUE TITLE
MqttService crash

### ISSUE THREAD

**Issue by YShein** [airmap/AirMapSDK-Android#2]
Hello, i received this issue from fabric.

Fatal Exception: java.lang.IllegalArgumentException: Invalid ClientHandle
       at org.eclipse.paho.android.service.MqttService.getConnection(MqttService.java:588)
       at org.eclipse.paho.android.service.MqttService.connect(MqttService.java:328)
       at org.eclipse.paho.android.service.MqttAndroidClient.doConnect(MqttAndroidClient.java:467)
       at org.eclipse.paho.android.service.MqttAndroidClient.access$200(MqttAndroidClient.java:76)
       at org.eclipse.paho.android.service.MqttAndroidClient$1.run(MqttAndroidClient.java:435)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

Platform Moto G4 Play with android 6.0.1

**Comment by zfort-vitalii** [comment]
Hi there i have same problem. I found the situation when you can got this issue.
Try to reproduce steps with code examples.
Happened when you try to do disable traffic 
`AirMap.disableTrafficAlerts();`

looks deeper 
`public static void disableTrafficAlerts() {
        getAirMapTrafficService().disconnect();
        getAirMapTrafficService().removeAllListeners();
    }`

deeper

` if (connectionState == ConnectionState.Disconnected || connectionState == ConnectionState.Connecting || !client.isConnected()) {...}`

issue happened here  `client.isConnected()` because within MqttAndroidClient check on connection happened with not fully understandable staff for me 
`  public boolean isConnected() {
        return this.clientHandle != null && this.mqttService != null && this.mqttService.isConnected(this.clientHandle);
    }`

`   public boolean isConnected(String clientHandle) {
        MqttConnection client = this.getConnection(clientHandle);
        return client.isConnected();
    }`

` private MqttConnection getConnection(String clientHandle) {
        MqttConnection client = (MqttConnection)this.connections.get(clientHandle);
        if(client == null) {
            throw new IllegalArgumentException("Invalid ClientHandle");
        } else {
            return client;
        }
    }`

Here we got exception. Why in case of null connected return as null and no MqttConnection got the exception. (Which not handled in your SDK)

Hope this help.

**Comment by wbrueg** [comment]
Hi all, the exception during AirMap.disableTrafficAlerts(); still exist in 2.0.0-beta.6. I reported via slack direct to Collin. The exception got thrown while following sequence:
 AirMap.disableTrafficAlerts();
 AirMap.endFlight(currentFlight, null);
If the flight get ended without the MqttConnection down we receive the exception. 
I think it would be helpful to get control about the connection by using a callback or make the AirMap.disableTrafficAlerts(); blocking, not returning until all related services down.
